# ESG METRIC DEFINITIONS (GRI Standards)

ESG_METRICS = [
    # Environmental
    {"id": "E01", "category": "Environmental", "name_en": "GHG Emissions Scope 1",
     "name_kr": "온실가스 배출량 (Scope 1)", "unit": "tCO2eq", "gri": "GRI 305-1",
     "valid_range": (0, 1e9)},
    {"id": "E02", "category": "Environmental", "name_en": "GHG Emissions Scope 2",
     "name_kr": "온실가스 배출량 (Scope 2)", "unit": "tCO2eq", "gri": "GRI 305-2",
     "valid_range": (0, 1e9)},
    {"id": "E03", "category": "Environmental", "name_en": "GHG Emissions Scope 3",
     "name_kr": "온실가스 배출량 (Scope 3)", "unit": "tCO2eq", "gri": "GRI 305-3",
     "valid_range": (0, 1e10)},
    {"id": "E04", "category": "Environmental", "name_en": "Total Energy Consumption",
     "name_kr": "총 에너지 사용량", "unit": "TJ", "gri": "GRI 302-1",
     "valid_range": (0, 1e6)},
    {"id": "E05", "category": "Environmental", "name_en": "Water Withdrawal",
     "name_kr": "용수 취수량", "unit": "톤", "gri": "GRI 303-3",
     "valid_range": (0, 1e10)},
    {"id": "E06", "category": "Environmental", "name_en": "Waste Generated",
     "name_kr": "폐기물 발생량", "unit": "톤", "gri": "GRI 306-3",
     "valid_range": (0, 1e8)},
    {"id": "E07", "category": "Environmental", "name_en": "Waste Recycling Rate",
     "name_kr": "폐기물 재활용률", "unit": "%", "gri": "GRI 306-4",
     "valid_range": (0, 100)},
    # Social
    {"id": "S01", "category": "Social", "name_en": "Total Employees",
     "name_kr": "총 임직원 수", "unit": "명", "gri": "GRI 2-7",
     "valid_range": (1, 1e6)},
    {"id": "S02", "category": "Social", "name_en": "Female Employee Ratio",
     "name_kr": "여성 임직원 비율", "unit": "%", "gri": "GRI 405-1",
     "valid_range": (0, 100)},
    {"id": "S03", "category": "Social", "name_en": "Lost Time Injury Rate",
     "name_kr": "산업재해율", "unit": "%", "gri": "GRI 403-9",
     "valid_range": (0, 100)},
    {"id": "S04", "category": "Social", "name_en": "Training Hours per Employee",
     "name_kr": "1인당 교육훈련 시간", "unit": "시간", "gri": "GRI 404-1",
     "valid_range": (0, 1000)},
    {"id": "S05", "category": "Social", "name_en": "Employee Turnover Rate",
     "name_kr": "이직률", "unit": "%", "gri": "GRI 401-1",
     "valid_range": (0, 100)},
    # Governance
    {"id": "G01", "category": "Governance", "name_en": "Independent Director Ratio",
     "name_kr": "사외이사 비율", "unit": "%", "gri": "GRI 2-9",
     "valid_range": (0, 100)},
    {"id": "G02", "category": "Governance", "name_en": "Board Meetings Held",
     "name_kr": "이사회 개최 횟수", "unit": "회", "gri": "GRI 2-9",
     "valid_range": (0, 100)},
    {"id": "G03", "category": "Governance", "name_en": "Female Board Member Ratio",
     "name_kr": "여성 이사 비율", "unit": "%", "gri": "GRI 405-1",
     "valid_range": (0, 100)},
    {"id": "G04", "category": "Governance", "name_en": "Anti-corruption Training Rate",
     "name_kr": "반부패 교육 이수율", "unit": "%", "gri": "GRI 205-2",
     "valid_range": (0, 100)},
]
